#include <SDL2/SDL.h>

extern SDL_Color MAIN_BACKGROUND_COLOR;
extern SDL_Color BACKGROUND_PART_ONE_COLOR;
extern SDL_Color BACKGROUND_PART_TWO_COLOR;
extern SDL_Color WAVES_OF_BACKGROUND_COLOR;

extern SDL_Color PINK_CASTLE_COLOR;
extern SDL_Color PINK_CASTLE_CENTER_COLOR;

extern SDL_Color GREEN_CASTLE_COLOR;
extern SDL_Color GREEN_CASTLE_CENTER_COLOR;

extern SDL_Color CREAM_CASTLE_COLOR;
extern SDL_Color CREAM_CASTLE_CENTER_COLOR;

extern SDL_Color BLUE_CASTLE_COLOR;
extern SDL_Color BLUE_CASTLE_CENTER_COLOR;

extern SDL_Color CASTLE_OUTLINE_COLOR;